FROM nvcr.io/nvidia/pytorch:25.08-py3

RUN pip install --no-cache-dir --upgrade pip==26.0.1 setuptools==80.10.2 wheel==0.46.3 ninja==1.13.0 cmake==4.3.1 "packaging==25.0"

RUN pip install --no-cache-dir vllm==0.19.0 flash-attn==2.7.4.post1 --no-build-isolation

ENV HF_HUB_ENABLE_HF_TRANSFER=1
ENV VLLM_USE_MODELSCOPE=false
